[package]
name = "algorithm_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "algorithm_lib"
path = "src/lib.rs"

[dependencies]
num-bigint = "0.4.5"
